### ISSUE TITLE
spark java.lang.RuntimeException: no default for type org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7

### ISSUE THREAD

**Issue by alg-jmx** [viirya/viirya.github.io#1]
I use spark version 2.1.1, df.except(dataSet) still throw exception like java.lang.RuntimeException: no default for type org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7, why? thanks

**Comment by viirya** [comment]
Just noticed this. This should be reported to Spark JIRA.
